---
- hosts: azure
  remote_user: jjmerelo
  sudo: yes
  tasks:
    - name: install packages
      apt: pkg={{ item}}
      with_items:
        - language-pack-en 
        - language-pack-es 
        - git 
        - curl 
        - build-essential 
        - libssl-dev
