---
- hosts: azure
  remote_user: jjmerelo
  sudo: yes
  tasks:
    - name: test connection
      ping:
      remote_user: jjmerelo
    - name: configure locale es
      apt: pkg=language-pack-es 
    - name: configure locale en
      apt: pkg=language-pack-en  
    - name: install git
      apt: pkg=git
